apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"react-app","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"react-app"}},"template":{"metadata":{"labels":{"app":"react-app"}},"spec":{"containers":[{"image":"react-app:latest","imagePullPolicy":"Never","name":"react-app","ports":[{"containerPort":80}]}]}}}}
  creationTimestamp: "2024-12-27T11:42:42Z"
  generation: 2
  name: multiverse-front-end
  namespace: default
  resourceVersion: "123927"
  uid: bb2f5147-da30-4f06-9d24-5bde4f60c7d2
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: multiverse-front-end
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: multiverse-front-end
    spec:
      containers:
      - image: react-app:latest
        imagePullPolicy: Never
        name: multiverse-front-end
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2024-12-27T11:46:15Z"
    lastUpdateTime: "2024-12-27T11:46:15Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-12-27T11:42:42Z"
    lastUpdateTime: "2024-12-27T11:46:15Z"
    message: ReplicaSet "react-app-5bb9b9f774" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
