apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiverse-game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multiverse-game
  template:
    metadata:
      labels:
        app: multiverse-game
    spec:
      containers:
      - name: multiverse-game
        image: multiverse-btg:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 80
        env:
        - name: NODE_ENV
          value: 'development'
---
apiVersion: v1
kind: Service
metadata:
  name: multiverse-game-service
spec:
  selector:
    app: multiverse-game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
